spring:
  application:
    name: arya-ucenter
  profiles:
    active: dev
server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always